### ISSUE TITLE
"IN THIS SECTION, THIS IS A FILE DIRECTORY REGARDED TO A DATASET THAT HAS BEEN TRANSFORM INTO PRINCIPAL COMPONENTS ANALYSIS MATRICES"

### ISSUE THREAD

**Issue by ghost** [serabiasin/PhonoCardioGram-Heart-Sound-Classification#1]
Hi, serabiasin.
Could you please provide the code to generate the .npy file, I am confused about this.
It would help me a lot, thank you very much!

**Comment by serabiasin** [comment]
dear [HuLeiY](https://github.com/HuLeiY),
 i have uploaded the source code to generate npy files, it is on Dataprep folder. First run the DATA_PREPARATION.ipynb and then run the script on WAVELET_TO_EIGEN_GENERATOR.ipynb (it should be wavelet to pca i forgot to rename it)..thank you

best regards,

**Comment by ghost** [comment]
dear&nbsp;serabiasin:
Thank you very much for getting back to me so quickly! good&nbsp;luck with your studies.



------------------ Original ------------------
From: Ahmad Alfi Adz-Dzikri ***@***.***&gt;
Date: Sun,Feb 27,2022 7:45 AM
To: serabiasin/PhonoCardioGram-Heart-Sound-Classification ***@***.***&gt;
Cc: HuLeiY ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [serabiasin/PhonoCardioGram-Heart-Sound-Classification] "IN THISSECTION, THIS IS A FILE DIRECTORY REGARDED TO A DATASET THAT HAS BEENTRANSFORM INTO PRINCIPAL COMPONENTS ANALYSIS MATRICES" (Issue #1)





 
dear HuLeiY,
 i have uploaded the source code to generate npy files, it is on Dataprep folder. First run the DATA_PREPARATION.ipynb and then run the script on WAVELET_TO_EIGEN_GENERATOR.ipynb (it should be wavelet to pca i forgot to rename it)..thank you
 
best regards,
